import fs from 'fs';
const base = '/home/reps/Videos/wow-ps';
const intros = {
Vanilla: `Vanilla (1.12.1) remains the foundation of the private-server scene, and our tracker reflects that. As of September 2, 2026 we list 109 total servers, with the Vanilla era — Vanilla, Vanilla+ and Classless combined — accounting for 42 tracked realms, the largest grouping on the site. Within that, 16 are tagged pure Vanilla for players who want unmodified 1.12, while 21 are Vanilla+ and 5 are Classless, each adding custom systems without leaving the old world. The list is reviewed September 2, 2026 and statuses shift as realms launch or close, so this page is a snapshot rather than a permanent ranking. If you are new, start from the [full tracker](/) and filter by Vanilla, then narrow by population and status. Pure blizzlike choices include [Elysium Project](/servers/elysium-project/), [Kronos V](/servers/kronos-v/), [Stonetavern](/servers/stonetavern/), [NycterMoon](/servers/nyctermoon/), [Ashen WoW](/servers/ashen-wow/) and [RetroWoW](/servers/retrowow/) for instant-60 fun, plus [SandWorlds](/servers/sandworlds/) and [Greyhaven](/servers/greyhaven/) for fresh progressive takes. For solo-friendly Vanilla, check [SoloCraft](/servers/solocraft/) which offers PartyBots and BattleBots companions. Vanilla+ widens the same world with new quests and balance — see [Project Legacy](/servers/project-legacy/), [Valanior](/servers/valanior/), [Vanilla+](/servers/vanilla-plus/), [Ravencraft](/servers/ravencraft/), [Felskorn](/servers/felskorn/) and [Octo WoW](/servers/octo-wow/) with its guide on [OctoWoW setup](/guides/octowow/). Classless experiments include [GrimfallWoW](/servers/grimfallwow/) and [Centurion — Legionnaire+](/servers/centurion-legionnaire/). Practical picks depend on pace: choose x1 progressive for the long road, x6 or instant-60 if you want raids immediately, and check Discord activity before committing because population matters more than feature lists. Dead or shuttered projects like Everlook are kept in the archive with shutdown dates, so you can see what failed and why. Use the era filter to compare Vanilla against [TBC](/tbc/), [WotLK](/wotlk/) and [Cataclysm](/cataclysm/) and watch the [status summary](/) for playable versus in-development versus dead. For a broader survey of custom Vanilla design, see our [Classic+ overview](/blog/what-is-classic-plus-plain-english/) and the [best Vanilla+ roundup](/blog/best-vanilla-plus-private-servers-2026/).`,

TBC: `The Burning Crusade (2.4.3) occupies a focused but durable corner of the tracker. As of September 2, 2026 we list 109 total servers and 7 of them are grouped under the TBC era, covering pure 2.4.3 realms plus select progressive takes that start in Outland. That makes TBC smaller than Vanilla or WotLK but large enough to offer real choice between blizzlike, high-rate and instant-70 playstyles. The page you are on shows the TBC era live, with status reviewed September 2, 2026, and each card links to a dedicated detail view at [/servers/…](/). For orientation, begin at the [full tracker](/) then filter by TBC and sort by status to separate playable from in-development. Playable highlights include [Rising Gods - Back2Basics](/servers/rising-gods-back2basics/) with its long-running German PvX community, [Moonwell](/servers/moonwell/) which peaked above 3k on its fresh realm, [Faebright](/servers/faebright/) running TBC on a WotLK client as RP-PvE, [BloodWoW (TBC)](/servers/bloodwow-tbc/) at x15 with BattleBots and cross-faction, and [Tirisgarde](/servers/tirisgarde/) offering instant-70 and custom PvP events. In development, the [Whitemane — Sunwell](/servers/whitemane-sunwell/) TBC realm under the Whitemane network is the most visible upcoming launch, sharing the network's QoL stack seen on [Whitemane — Gilneas](/servers/whitemane-gilneas/) in Cataclysm. If you want historical context, TBC emulation has moved from older MaNGOS cores to modern backports, and our timeline covers setbacks like [Felmyst](/servers/felmyst/) which remains offline since 2023. When choosing, decide pace first: x1 blizzlike for attunement chains and Karazhan progression, x15 or instant-70 if you want to raid quickly, and always verify population tier and last-checked date on the card. Links between eras help: compare TBC sizing against [Vanilla](/vanilla/) at 42 grouped realms and [WotLK](/wotlk/) at 37, or step forward to [Cataclysm](/cataclysm/) and [MoP](/mop/) for later expansions. For methodology notes on how we track status, see the tracker home and the [news archive](/news/) for TBC launch posts.`,

WotLK: `Wrath of the Lich King (3.3.5a) is the busiest expansion in private servers, and the numbers show it. As of September 2, 2026 the tracker lists 109 servers in total and 37 of them sit in the WotLK era, the single largest pure-expansion bucket. That scale comes from a mature core ecosystem — TrinityCore and AzerothCore have been iterated for over a decade — so WotLK realms tend to be the most script-complete, best documented, and most varied. Review date for this page is September 2, 2026, with each realm card showing status, population tier and last-checked date. Start at the [full tracker](/) and filter to WotLK to see playable, in-development and dead together, then open any [/servers/…](/) detail for related history. If you want blizzlike, consider [Warmane](/servers/warmane/) for sheer population, [Chromiecraft](/servers/chromiecraft/) for staged, upstreamed fixes, [Sunwell.pl](/servers/sunwell-pl/), [Dalaran-WoW](/servers/dalaran-wow/), [TrueWoW](/servers/truewow/), [WoW-Mania](/servers/wow-mania/) and the ultra-clean [Elwynnkeep](/servers/elwynnkeep/) with zero custom content. Progressive options include [Eternal Gaming](/servers/eternal-gaming/), [Maelstrom (Millenium)](/servers/maelstrom-millenium/) which caps at 60 until late August, and [Project Alterac](/servers/project-alterac/) in phased rollout. For solo or small-group play, see [TheraWoW](/servers/therawow/), [OnlyFunsWoW](/servers/onlyfunswow/), [Stormgarde](/servers/stormgarde/), [Galaxyofdrone WoW](/servers/galaxyofdrone-wow/), [Warstorm](/servers/warstorm/) and [Triumvirate-WoW](/servers/triumvirate-wow/) which added ICC and Mythic+ Season 2 in August. High-rate and fun varieties include [Sirus](/servers/sirus/) with 6–13k online and custom races, [UnlimitedWoW](/servers/unlimited-wow/) at level 255, and [Azeroth Universe](/servers/azeroth-universe/). Watch for upcoming launches like [Whitemane — Frostmourne](/servers/whitemane-frostmourne/) slated September 9. When picking, weigh population over feature lists, check pay-to-win policies, and cross-compare with [Vanilla](/vanilla/), [Cataclysm](/cataclysm/) and [Legion](/legion/) to avoid choosing solely on nostalgia. Deeper guides live at [best WotLK servers 2026](/blog/best-wotlk-private-servers-2026/) and [best WotLK for solo](/blog/best-wotlk-for-solo/).`,

Cataclysm: `Cataclysm (4.3.4) has rebounded into a stable niche, anchored by a few large networks and several smaller blizzlike realms. As of September 2, 2026 the tracker counts 109 total servers and 7 of them are grouped under the Cataclysm era, a compact but active set where most population concentrates on two or three networks. Status on this page is reviewed September 2, 2026 and each card exposes status, population and last-checked date with a link to its [/servers/…](/) detail. If you are deciding, open the [full tracker](/) and isolate Cataclysm, then scan playable versus in-development to avoid waiting on a realm that has not launched. The leading cluster is [Whitemane — Gilneas](/servers/whitemane-gilneas/) and [Whitemane — Maelstrom](/servers/whitemane-maelstrom/) on the Whitemane network, both 4.3.4 with 4k+ concurrent and extensive QoL, custom legendaries and solo-queue PvP; they are the default recommendation for players who want a crowded, modernized Cata experience. The independent alternative is [Atlantiss](/servers/atlantiss/) which acts as the flagship of the Atlantiss-Tauri network after its February 2026 relaunch and also operates connected [MoP](/mop/) and [TBC](/tbc/) realms. TwinStar's dedicated Cata realm [Apollo II](/servers/apollo-ii/) remains playable for those who prefer a lighter custom footprint, while [WOW-COLOMBIA](/servers/wow-colombia/) and [WarSages](/servers/warsages/) serve the long-running Spanish-language Cata community with seasonal arena and dragon-era content. One notable in-development Cata project is [Hour of Twilight](/servers/hour-of-twilight/) targeting 2026. When weighing Cata against neighboring eras, compare the 7 Cata realms to 37 in [WotLK](/wotlk/) and 42 grouped in [Vanilla](/vanilla/), and consider whether you want Cata systems like transmog, reforging and LFR versus the older talent trees. For new players, start on a high-population network if you value dungeon finder speed, or pick Atlantiss or Apollo II if you prioritize blizzlike scripting over QoL extras. Follow-up context and network explainers live in our [news](/news/) and [blog](/blog/) sections, and network-wide posts such as the Whitemane explainer connect the dots between expansions.`,

MoP: `Mists of Pandaria (5.4.8) is the smallest retail-era grouping before Legion, with tight competition among two networks. As of September 2, 2026 the tracker lists 109 servers total and only 4 of them fall under the MoP era, which makes selection straightforward but also means population and polish vary sharply. This page is reviewed September 2, 2026 and each card links to its [/servers/…](/) detail where you can check status, population tier and update date. Begin at the [full tracker](/) filtered to MoP to compare playable against in-development without guessing. The most active playable choice is [Helios](/servers/helios/) on TwinStar, a 5.4 MoP realm with Siege of Orgrimmar live and cross-faction enabled, making it the natural entry point for players who want current-tier raiding without custom systems. Atlantiss maintains a connected MoP 5.4.8 realm alongside its [Cataclysm](/cataclysm/) flagship [Atlantiss](/servers/atlantiss/), useful if you want to hop between eras inside the same network. On the Whitemane side, [Whitemane — Stormstout](/servers/whitemane-stormstout/) is in development as a 5.4.8 realm that will share the network's QoL stack seen on [Whitemane — Gilneas](/servers/whitemane-gilneas/) and the upcoming [Whitemane — Frostmourne](/servers/whitemane-frostmourne/) WotLK realm, so it is worth watching if you prefer a launch with established infrastructure. The second TwinStar MoP effort, [Perseus](/servers/perseus/), is also in development as a fresh MoP, and the closure of [Stormforge (Mistblade)](/servers/stormforge-mistblade/) in May 2026 after a cease-and-desist left a gap that these new realms aim to fill. Choosing MoP often comes down to whether you want immediate raiding on Helios or to wait for a fresh start on Perseus or Stormstout. Cross-check against neighboring eras: MoP systems like challenge modes and flexible raiding sit between [Cataclysm](/cataclysm/) at 7 realms and [Legion](/legion/) at 6, and far below [WotLK](/wotlk/) at 37 and [Vanilla](/vanilla/) at 42 in sheer option count. See [news](/news/) and [blog](/blog/) for MoP progression posts.`,

Legion: `Legion (7.3.5) is the strongest modern-expansion option on the tracker, led by two durable networks with very different philosophies. As of September 2, 2026 we track 109 servers overall and 6 of them are grouped under the Legion era, making Legion the largest modern bucket ahead of [TWW](/tww/) at 3 and [MoP](/mop/) at 4. This page is reviewed September 2, 2026 and each Legion card includes status, population and last-checked date plus a link to its [/servers/…](/) detail for related history. Start from the [full tracker](/) filtered to Legion to separate playable from in-development quickly. The most veteran choice is [Tauri](/servers/tauri/) which runs Legion PvE with a long track record and conservative blizzlike approach. At the other end of the scale, [uWoW](/servers/uwow/) has operated a Legion 7.3.5 network since 2009 and remains the longest-lived Legion provider with about 3.3k Discord members. For German-hosted and high-rate variety, [ArgusWoW](/servers/arguswow/) offers three rate tiers (x100, x3, x1) across five raid tiers, while [LegionPlus](/servers/legionplus/) adds fated raids, custom bosses, hardcore and allied races with timewalking, and [Hellgarve](/servers/hellgarve/) focuses on solo-friendly artifacts with 1–3x XP. The newest entry, [Felsong](/servers/felsong/) launched Spring 2025 and will soon merge into the Firestorm ecosystem alongside [Firestorm](/servers/firestorm/) itself. If you are comparing eras, Legion's 6 realms sit well below the 42 grouped in [Vanilla](/vanilla/) and 37 in [WotLK](/wotlk/) but offer modern systems — artifact weapons, mythic+, world quests — that older eras lack. Pick Tauri or uWoW for stability and scripting depth, Argus or LegionPlus for faster or custom progression, and Hellgarve if you mainly play alone. Background on modern core development and Legion-specific coverage appears in [news](/news/) and [blog](/blog/) archives.`,

TWW: `The War Within (TWW) is the newest retail-expansion footprint on the tracker and still early-stage. As of September 2, 2026 we list 109 total servers and only 3 of them are grouped under the TWW era, reflecting how fresh retail-to-private backporting is for this content. Status here is reviewed September 2, 2026 and each card points to its [/servers/…](/) detail with status, population and update information. The pragmatic starting point is the [full tracker](/) filtered to TWW to avoid confusing TWW with nearby Dragonflight or Midnight builds that may be labeled differently. The dominant playable option today is [Firestorm](/servers/firestorm/) which runs a TWW Dornogal realm alongside its BFA Reforged project launching August 31, plus legacy realms, peaking around 2.5–4k online and with over 3600 players queued for the new season. The second playable choice is [Dragonborn WoW](/servers/dragonborn-wow/) which launched a Dragonflight realm in February 2026 and is tracked under TWW grouping for modern-expansion browsing, with an estimated 100–500 population and active updates. In development, [Luntares](/servers/luntares/) is already in beta for Midnight, the next retail expansion, which will succeed TWW and is worth watching if you want to follow the bleeding edge rather than current leveling. Because TWW is small, most players cross-shop it against [Legion](/legion/) with 6 realms or [Cataclysm](/cataclysm/) with 7 if they want modern systems with larger communities, or against [WotLK](/wotlk/) at 37 for maximum realm choice and stability. If you choose TWW now, expect faster patch churn and occasional scripting gaps compared with older eras, and favor Firestorm if you need population density and frequent updates. Broader context on modern expansion launches lives in [news](/news/) and our [blog](/blog/) coverage, including adjacent era guides for [MoP](/mop/) and [Vanilla](/vanilla/).`,

Multi: `Multi-expansion networks are where a single provider keeps parallel realms for several eras under one account. As of September 2, 2026 the tracker lists 109 servers and 1 of them is classified directly as Multi — [WoW Circle](/servers/wow-circle/) — though the true multi-realm experience also appears through large networks that span eras without using the Multi tag. This page is reviewed September 2, 2026 and each Multi card links to its [/servers/…](/) detail and related history entries. Start at the [full tracker](/) to compare Multi against single-era filters like [Vanilla](/vanilla/), [TBC](/tbc/), [WotLK](/wotlk/), [Cataclysm](/cataclysm/), [MoP](/mop/), [Legion](/legion/) and [TWW](/tww/). The canonical example, [WoW Circle](/servers/wow-circle/), operates 13 realms ranging from TBC through Dragonflight with a large Russian-speaking community and is the only realm in the data set currently tagged Multi, making it the simplest way to stay inside one ecosystem while swapping expansions. Beyond that tag, the same pattern is visible in networks tracked elsewhere: TwinStar runs [Apollo II](/servers/apollo-ii/) in Cataclysm, [Helios](/servers/helios/) and the upcoming [Perseus](/servers/perseus/) and [Whitemane — Stormstout](/servers/whitemane-stormstout/) in MoP, plus [Whitemane — Sunwell](/servers/whitemane-sunwell/) in TBC; Atlantiss threads [Atlantiss](/servers/atlantiss/) Cata together with MoP and TBC realms; Whitemane itself covers Cataclysm via [Whitemane — Gilneas](/servers/whitemane-gilneas/) and [Whitemane — Maelstrom](/servers/whitemane-maelstrom/) and WotLK via [Whitemane — Frostmourne](/servers/whitemane-frostmourne/); Firestorm bridges [Firestorm](/servers/firestorm/) TWW and legacy; Tauri bridges [Tauri](/servers/tauri/) Legion with its broader network. If you value one login, shared forums and cross-era events, Multi networks reduce friction versus juggling separate providers. If you prefer era-specific polish, a dedicated [WotLK](/wotlk/) or [Vanilla](/vanilla/) realm may still script that era more deeply than a broad network. For network explainers see [Whitemane network](/blog/whitemane-network-explained/) and browse [news](/news/).`,
};
for (const [era, body] of Object.entries(intros)) {
  const slug = era.toLowerCase();
  const words = body.split(/\s+/).filter(Boolean).length;
  console.log(era, words);
  const md = `---
title: "${era} Private Servers — Expansion Guide"
date: 2026-09-02
category: guides
summary: "${era} expansion guide — ${slug} servers, picks and population as of September 2, 2026."
---

${body}
`;
  fs.writeFileSync(`${base}/src/expansion-intros/${slug}.md`, md);
}
console.log('done');
