module.exports = {
    name: "OctoWoW",
    signup: "https://octowow.st/",
    source: "Static Ninja's OctoWoW Modern Client Guide",
    tools: [
        { "name": "OctoUpdater", "desc": "Client and addon auto-updater utility.", "url": "https://github.com/rebasedkon/octo-updater" },
        { "name": "SuperApi", "desc": "Required dependency for SuperWoW functionality.", "url": "https://github.com/balakethelock/SuperApi" },
        { "name": "Project Reforged", "desc": "HD graphics overhaul for 1.12 clients.", "url": "https://projectreforged.github.io/vanilla" },
        { "name": "Reshade", "desc": "Graphics overhaul, shaders, and setup.", "url": "https://reshade.me/" }
    ],
    essential: [
        { "name": "ShaguTweaks", "desc": "Lightweight QoL tweaks for the default UI.", "url": "https://github.com/Dusk-92/ShaguTweaks" },
        { "name": "pfUI", "desc": "Full user interface replacement for 1.12 clients.", "url": "https://github.com/brues-code/pfUI" }
    ],
    recommended: [
        { "name": "InstanceJournal", "desc": "Instance journal", "url": "https://github.com/Arthur-Helias/InstanceJournal" },
        { "name": "Supercleveroid", "desc": "Enhanced macros (dynamic tooltips, conditional execution)", "url": "https://github.com/jrc13245/SuperCleveRoidMacros" },
        { "name": "TankPlates", "desc": "Tank nameplates", "url": "https://github.com/MarcelineVQ/TankPlates" },
        { "name": "LazyPig", "desc": "Misc convenience addon", "url": "https://github.com/jrc13245/_LazyPig" },
        { "name": "Lern2spell", "desc": "Spell-learning reminders", "url": "https://github.com/crazypoultry/Wow1.12.1_Addons_Collection/tree/master/Lern2Spell_r15902" },
        { "name": "LazySpell", "desc": "Spell automation", "url": "https://github.com/laytya/Lazyspell" },
        { "name": "Adapt", "desc": "3D unit frame portraits (download via download-directory)", "url": "https://github.com/crazypoultry/Wow1.12.1_Addons_Collection/tree/master/Adapt_v1.5" },
        { "name": "AddonOrganizer", "desc": "Addon manager", "url": "https://github.com/Otari98/AddOnOrganizer" },
        { "name": "AegisExchange", "desc": "Mail/exchange addon", "url": "https://github.com/Torchlite-bit/Aegis_Exchange" },
        { "name": "AuctionQueryThrottle", "desc": "Auction house throttling", "url": "https://github.com/brues-code/AuctionQueryThrottle" },
        { "name": "AtlasLoot", "desc": "Instance loot browser", "url": "https://github.com/Otari98/AtlasLoot" },
        { "name": "AttackBarTimer", "desc": "Attack bar timing", "url": "https://github.com/Road-block/AttackBar" },
        { "name": "Bagshui", "desc": "Bag management", "url": "https://github.com/HeartNotSmart/Bagshui" },
        { "name": "BetterCharacterStats", "desc": "Improved character stats panel", "url": "https://github.com/pepopo978/BetterCharacterStats" },
        { "name": "Chatsuey", "desc": "Chat enhancements", "url": "https://github.com/ScottHamper/chatsuey" },
        { "name": "Chronometer", "desc": "Buff/debuff timers", "url": "https://github.com/Judo101/Chronometer" },
        { "name": "GreedMeter", "desc": "DPS meter", "url": "https://github.com/iGreed1993/GreedMeter" },
        { "name": "LevelRange", "desc": "Level range display", "url": "https://github.com/Spartelfant/LevelRange-Turtle" },
        { "name": "Mik's Scrolling Battle Text", "desc": "Scrolling combat text", "url": "https://github.com/roby-brok/MikScrollingBattleText" },
        { "name": "MinimapButtonBag", "desc": "Minimap button management", "url": "https://github.com/McPewPew/MinimapButtonBag" },
        { "name": "ModernSpellBook", "desc": "Modern spell book layout", "url": "https://github.com/vegeta1k95/ModernSpellBook" },
        { "name": "NiceDamage", "desc": "Damage display", "url": "https://github.com/Wurmschwanz/NiceDamage-1.12" },
        { "name": "OctoSpec", "desc": "Spec/talent build importer + item scorer", "url": "https://github.com/iGreed1993/OctoSpec" },
        { "name": "OmniCC", "desc": "Cooldown countdowns", "url": "https://github.com/Otari98/OmniCC" },
        { "name": "Outfitter", "desc": "Outfit/gear manager", "url": "https://github.com/pepopo978/Outfitter" },
        { "name": "SimpleActionSets", "desc": "Action bar sets", "url": "https://github.com/pepopo978/SimpleActionSets" },
        { "name": "Puppeteer", "desc": "Unit frames addon (healer-friendly, VuhDo/Healbot alternative)", "url": "https://github.com/OldManAlpha/Puppeteer" },
        { "name": "QuestAnnouncer", "desc": "Quest progress announcements (download via download-directory)", "url": "https://github.com/crazypoultry/Wow1.12.1_Addons_Collection/tree/master/QuestAnnouncer_r17551" },
        { "name": "QuestItem", "desc": "Quest item use", "url": "https://github.com/wow-vanilla-addons/QuestItem" },
        { "name": "RestedXP", "desc": "Leveling guide", "url": "https://github.com/tyllyn/Octo-Rested" },
        { "name": "TurtleMail", "desc": "Mail addon", "url": "https://github.com/sica42/TurtleMail" },
        { "name": "AegisCourier", "desc": "Mail addon (recommended)", "url": "https://github.com/Torchlite-bit/Aegis_Courier" },
        { "name": "MatrixMaps", "desc": "Map display", "url": "https://github.com/dabblez/MatrixMaps" }
    ]
};