const SERVERS = require("./_data/servers.js");
const NEWS = require("./_data/news.js");
const LINKS = require("./_data/links.js");
const HISTORY = require("./_data/history.js");

// Generates _site/data.js so app.js sees the same global consts as before.
// Edit src/_data/*.js, not this file.
module.exports = {
    data: { permalink: "/data.js", eleventyExcludeFromCollections: true },
    render() {
        return [
            "// generated by Eleventy from src/_data — edit there, not here",
            `const SERVERS = ${JSON.stringify(SERVERS)};`,
            `const NEWS = ${JSON.stringify(NEWS)};`,
            `const LINKS = ${JSON.stringify(LINKS)};`,
            `const HISTORY = ${JSON.stringify(HISTORY)};`,
            ""
        ].join("\n\n");
    }
};
