const SERVERS = require("./_data/servers.js");
const LINKS = require("./_data/links.js");
const HISTORY = require("./_data/history.js");

// Generates _site/data.js so app.js sees the same global consts as before.
// SERVERS/LINKS/HISTORY come from src/_data/*.js; NEWS is derived from the
// src/news/*.md markdown collection. Edit those, not this file.
module.exports = {
    data: { permalink: "/data.js", eleventyExcludeFromCollections: true },
    render(data) {
        const news = [...(data.collections.news || [])].reverse().map(n => ({
            title: n.data.title,
            url: n.data.link || n.url
        }));
        return [
            "// generated by Eleventy from src/_data and src/news — edit there, not here",
            `const SERVERS = ${JSON.stringify(SERVERS)};`,
            `const NEWS = ${JSON.stringify(news)};`,
            `const LINKS = ${JSON.stringify(LINKS)};`,
            `const HISTORY = ${JSON.stringify(HISTORY)};`,
            ""
        ].join("\n\n");
    }
};
