const SERVERS = require("./_data/servers.js");
const LINKS = require("./_data/links.js");
const HISTORY = require("./_data/history.js");
const { STATUS, HTYPE, ERA, ERA_ORDER, ICONS, slugify, matches, groupByEra, countByStatus } = require("./_data/vocab.js");

// Generates _site/data.js so app.js sees the same global consts as before.
// SERVERS/LINKS/HISTORY come from src/_data/*.js; NEWS is derived from the
// src/news/*.md markdown collection. Edit those, not this file.
module.exports = {
    data: { permalink: "/data.js", eleventyExcludeFromCollections: true },
    render(data) {
        const news = [...(data.collections.news || [])].reverse().map(n => ({
            title: n.data.title,
            url: n.data.link || n.url
        }));
        return [
            "// generated by Eleventy from src/_data and src/news — edit there, not here",
            `const SERVERS = ${JSON.stringify(SERVERS)};`,
            `const NEWS = ${JSON.stringify(news)};`,
            `const LINKS = ${JSON.stringify(LINKS)};`,
            `const HISTORY = ${JSON.stringify(HISTORY)};`,
            `const VOCAB = { STATUS: ${JSON.stringify(STATUS)}, HTYPE: ${JSON.stringify(HTYPE)}, ERA: ${JSON.stringify(ERA)}, ERA_ORDER: ${JSON.stringify(ERA_ORDER)}, ICONS: ${JSON.stringify(ICONS)}, slugify: ${slugify.toString()}, matches: ${matches.toString()}, groupByEra: ${groupByEra.toString()}, countByStatus: ${countByStatus.toString()} };`,
            ""
        ].join("\n\n");
    }
};
